/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeckApp: typeof import('./../components/Deck/DeckApp.vue')['default']
    DeckSS: typeof import('./../components/Deck/DeckSS.vue')['default']
    DeckUser: typeof import('./../components/Deck/DeckUser.vue')['default']
    HeaderView: typeof import('./../components/HeaderView.vue')['default']
    IMdiAccountCircle: typeof import('~icons/mdi/account-circle')['default']
    IMdiApplication: typeof import('~icons/mdi/application')['default']
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IMdiLoading: typeof import('~icons/mdi/loading')['default']
    IMdiMonitorScreenshot: typeof import('~icons/mdi/monitor-screenshot')['default']
    LoadingView: typeof import('./../components/LoadingView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
