name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_SYSROOT_DIR: /
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@b32f140b0c872d58512e0a66172253c302617b90

      - name: Rust Target
        run: |
          rustup update stable

      - name: Setup rust cache
        uses: Swatinem/rust-cache@640a22190e7a783d4c409684cea558f081f92012
        with:
          prefix-key: "${{ runner.os }}-deck-ss-explorer-build-rust"

      - name: Prepare pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup frontend cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: backend/frontend/node_modules
          key: ${{ runner.os }}-deck-ss-explorer-build-frontend-${{ hashFiles('backend/frontend/package-lock.json') }}

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build backend-frontend
        run: |
          pushd backend/frontend
          npm install
          npm run build-only
          popd

      - name: Build backend
        run: |
          pushd backend
          cargo build --locked --release --verbose --all
          chmod +x target/release/backend
          mkdir -p out
          cp target/release/backend out/
          popd

      - name: Build frontend
        run: |
          pnpm run build

      - name: Package
        run: |
          python3 scripts/package-contents.py

      - name: Upload artifact
        uses: actions/upload-artifact@ef09cdac3e2d3e60d8ccadda691f4f1cec5035cb
        with:
          name: deck-screenshot-explorer
          path: |
            deck-screenshot-explorer-v*.zip
